# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Install minimal dependencies and cleanup
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc default-libmysqlclient-dev \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project
COPY pyproject.toml requirements.txt requirements-dev.txt README.md .env.template ./
COPY src ./src

# Install runtime dependencies and package
RUN pip install --no-cache-dir -r requirements.txt \
 && pip install --no-cache-dir .

# Expose standard streams
ENTRYPOINT ["oceanbase_mcp_server"]
CMD ["--transport","stdio"]
